### ISSUE TITLE
Template suggestion: truthy

### ISSUE THREAD

**Issue by wmaurer** [ipatalas/vscode-postfix-ts#10]
Thanks a lot for this extension!

I would find a 'truthy' template useful, i.e. so that `expr` becomes `!!expr`.
What do you think?

**Comment by ipatalas** [comment]
Well, I'm not using this construction very often but still I will have something for you.
I do have a plan to allow user defined templates. It should be relatively easy to implement given current implementation.
I'll give it a try this weekend.
Stay tuned.

**Comment by ipatalas** [comment]
Ok, basic custom templates are ready! Update the extension to 1.6.0 first.

For what you need just add the following to your workspace/user settings:

```JSON
"postfix.customTemplates": [{
	"name": "truthy",
	"body": "!!{{expr}}",
	"description": "!!expr",
	"when": [
		"expression", "function-call", "identifier"
	]
}]
```

Let me know if that helped.

**Comment by wmaurer** [comment]
Hey cheers, it works really well! 
Thanks a lot for putting the effort into this new feature.
