### ISSUE TITLE
Some templates missing inside a function

### ISSUE THREAD

**Issue by ipatalas** [ipatalas/vscode-postfix-ts#105]
Almost released a buggy version :)

When triggered inside a function the number of templates is very limited:
![image](https://user-images.githubusercontent.com/2623329/214950546-55f0c365-74f1-4c2f-ab09-20cd37b0f644.png)

However if I do the same with currently released version it's alright:
![image](https://user-images.githubusercontent.com/2623329/214950629-55e73b45-99a9-4036-81a6-becabf4c10e5.png)

> **Note**: don't forget to add a regression test for that

**Comment by ipatalas** [comment]
Narrowed it down to:
![image](https://user-images.githubusercontent.com/2623329/214952998-34108d49-b7fd-432a-ad2a-40e0b6d5aad5.png)

**Line 6**. shows limited templates
**Line 8**. shows everything correctly

So not necessarily in a function but what matters is the code right after the current line. Seems like taking full source before and after is not stable yet.

**Comment by ipatalas** [comment]
@zardoy do you remember why did you introduce that in the first place?
I found the commit: https://github.com/zardoy/vscode-postfix-ts/commit/d5233e70f7a1bbe3fce8b64ae53d3237467fb94e
However it doesn't say exactly what it fixes. Do you remember any examples?

It now becomes a little bit of a problem because the expression under the cursor (right after dot) can span across multiple lines depending on what code is in next line:
![image](https://user-images.githubusercontent.com/2623329/215107425-48516d60-bb5a-4c94-847f-6279ac433bc8.png)
See yellow highlight on the left.

When I put a semicolon to explicitly separate statements then it works fine but nobody starts writing lines with semicolons ;) and in some projects we have convention without semicolons at all.
![image](https://user-images.githubusercontent.com/2623329/215107651-6d033470-5e5a-4049-80c1-879076a143b9.png)

Also it depends on what's in the next line:
![image](https://user-images.githubusercontent.com/2623329/215107947-163d008d-f766-4072-8150-0a5e18ce6acd.png)
In this case this statement couldn't span across next line because it wouldn't make sense.

If I will know what was this change fixing then it should be much easier to figure out a proper solution for that.

**Comment by zardoy** [comment]
> However it doesn't say exactly what it fixes. 

No it does, see commit body (#71)

Have no idea why I didn't add test as I knew exact case

**Comment by ipatalas** [comment]
> No it does, see commit body (https://github.com/ipatalas/vscode-postfix-ts/issues/71)

Oh shoot, you're right, GH should do better job showing the body :D 

All right, I'll think about it but from first sight it seems like maybe it's better to use old approach by default and full source when needed. Just need to think how to define 'when needed' ;)

**Comment by ipatalas** [comment]
Fixed in https://github.com/ipatalas/vscode-postfix-ts/commit/d5e2d295264e64a019e5dc9c58173c538b8a502e

Took me a while to figure this out as fixing one thing was always breaking another :) Had few attempts every other day to forget last solution and start over with fresh mind. Turned out I was looking in a wrong place :)
