### ISSUE TITLE
Exclude intermediate step from editor history

### ISSUE THREAD

**Issue by mrmlnc** [ipatalas/vscode-postfix-ts#11]
Good idea and realization! Thanks 🌮 

Now, if I want to cancel the action of the plugin I press <kbd>cmd + Z</kbd>. But in the story editor saved intermediate step (like `log` or `if`).

Just look at GIF

![vscode](https://user-images.githubusercontent.com/7034281/31756992-9f8a3b52-b4af-11e7-84fb-e1e646fbb8dd.gif)

I remember that this was already decided in Emmet, but I can't find how to do it.

//cc @jrieken as VS Code Hero :P

**Comment by ipatalas** [comment]
Thanks for your comment.

It's true about the Undo, but honestly I don't know if it can be changed. Most of those completions are single operations but somehow VS Code remembers the edits separately.
Not sure if I can do anything with that. Maybe @jrieken can advise. He helped me a lot earlier with this extension.

**Comment by jrieken** [comment]
Unfortunately no.

**Comment by mrmlnc** [comment]
Well, feel free to close if you wanted 🖌

**Comment by ipatalas** [comment]
Forgot to do so :)
