### ISSUE TITLE
Can i pass the body of custom template as array of string type?

### ISSUE THREAD

**Issue by eenaree** [ipatalas/vscode-postfix-ts#115]
When creating templates with many rows in the body, using newline characters like '\n' and '\t' can make the template look messy and less visually appealing.

```json
"postfix.customTemplates": [
	{
      "name": "class extends",
      "body": "class ${1:{{expr:capitalize}}Extended} extends {{expr:capitalize}} {\n\tconstructor($2) {\n\t\tsuper($3)$0\n\t}\n}\n",
      "description": "extends Class Declaration",
      "when": ["identifier"]
    }
]
```

Instead of using string, can i pass the body of custom template as array of string type, like vscode's snippets?

for example,

```json
{
  "body": [
    "class ${1:{{expr:capitalize}}Extended} extends {{expr:capitalize}} {",
    "  constructor($2) {",
    "    super($3)$0",
    "  }",
    "",
  ]
}
```

**Comment by ipatalas** [comment]
Well, I never thought of that but it's a great idea! Also very simple to implement - took me 5-10 minutes to get it working.
A new version (1.13.1) has been just released with that change. You can now either pass it as single string or array of strings. 
I had to leave single string option for backward compatibility. Enjoy!

**Comment by eenaree** [comment]
Thanks for listening to my thoughts. 
Depending on the complexity of the template, I think we can select the type of value to pass. Thanks again!
