### ISSUE TITLE
lowercase/uppercase doesn't work

### ISSUE THREAD

**Issue by dylanphantixr** [ipatalas/vscode-postfix-ts#119]
```
{
      "name": "useState",
      "body": "const [{{expr}}, set{{expr:uppercase}}] = React.useState();",
      "when": []
  }
```

Starting from your capitalize example, I changed capitalize to uppercase, and it doesn't work.
It results in:
```
const [myState, set{{expr:uppercase}}] = React.useState();
```

lowercase doesn't work either

**Comment by dylanphantixr** [comment]
Oh I see in the code that it's `lower` and `upper`, not lowercase and uppercase. Might be good to update the readme/docs.

**Comment by ipatalas** [comment]
Good catch, fixed it in the README, thanks!
