### ISSUE TITLE
.undefined should create a "typeof" check

### ISSUE THREAD

**Issue by harrison-symes** [ipatalas/vscode-postfix-ts#27]
Current postfixing `.undefined` to the end of an entry fixes it to:

``` 
if (value === undefined) {

}
```

It is safer to check `if (tpyeof value === "undefined") {` instead.

The same goes for `notundefined`

Alternatively, create a new postfix for this specific typeof scenario

**Comment by ipatalas** [comment]
I'm not a big fan of that approach. This is why: https://www.codereadability.com/how-to-check-for-undefined-in-javascript/

I'll think about introducing a setting that would toggle one or the other version. I really doubt anyone would use both versions in the same project.

In the meantime you can play around with custom templates to get this done:
```JSON
"postfix.customTemplates": [
    {
      "name": "undef",
      "body": "if (typeof {{expr}} === 'undefined') {\n${0}\n}",
      "description": "if (typeof expr === 'undefined')",
      "when": [
        "identifier",
        "expression"
      ]
    }
  ]
```

**Comment by ipatalas** [comment]
![image](https://user-images.githubusercontent.com/2623329/69006488-adab0280-092f-11ea-9da7-83b46afede88.png)

Release should be ready quite soon.
