### ISSUE TITLE
Custom templates don't show up in the autocomplete menu

### ISSUE THREAD

**Issue by aaronmcadam** [ipatalas/vscode-postfix-ts#32]
Here's my custom template:

```json
"postfix.customTemplates": [
    {
      "name": "dl",
      "description": "detailed log",
      "body": "console.log('{{expr}}', {{expr}});$0",
      "when": [
        "expression"
      ]
    }
  ]
```

See this screen capture:

![CleanShot 2020-02-12 at 11 24 49](https://user-images.githubusercontent.com/37928/74330859-5da2d700-4d8a-11ea-8ad1-256687680474.gif)

**Comment by ipatalas** [comment]
Hi, first of all thanks for a very good bug report. I wish all of them were that descriptive :)

Ok, I see two potential problems here. 

One is that `app.` is not an `expression` but just an `identifier` type of context. That's all described [here](https://github.com/ipatalas/vscode-postfix-ts#template-conditions) in details. 
If that's not self explanatory, let me know, I'll try to rephrase.

Having that in mind you should update the config as follows:
```JS
"postfix.customTemplates": [
    {
      "name": "dl",
      "description": "detailed log",
      "body": "console.log('{{expr}}', {{expr}});$0",
      "when": [
        "expression",
        "identifier"
      ]
    }
  ]
```

`expression` will still be handy for `object.property.value` or `array[index]` code.


The other, less obvious issue is that while trying to repro the problem I have found out that only workspace configuration is taken into account so if this sits in your user settings.json then it won't work. As a workaround just place it into workspace settings.json. I will fix that in next release.

**Comment by aaronmcadam** [comment]
Thanks so much @ipatalas, it works now by adding support for identifiers. While the docs are good, I think it might be useful to show some example custom templates to help people learn.
