### ISSUE TITLE
Incorrect insertion when in mid of expression

### ISSUE THREAD

**Issue by zardoy** [ipatalas/vscode-postfix-ts#60]
Hey! I have the following snippet:

```
{
    "name": "entries",
    "description": "",
    "body": "Object.entries({{expr}})",
    "when": ["identifier", "expression", "function-call"]
}
```

And I usually like to use it in the middle of expression to fix TS errors like this:

```
a.entries.a
```

However:

- Writing `a.a` and then adding `.entries` after first `a` without retriggering completions inserts `Object.entries(a.).a` (would be ideal if it didn't place that trailing `.`)

- Writing `a.ent.a.` (or `a.entries.a`) and only then triggering completions inserts postfix itself e.g. `Object.entries(a.ent)a`.

**Comment by ipatalas** [comment]
Oh, this might be tricky as the idea was to only analyze what's before the triggering postfix template. That means it was always meant to be used at the end of the expression so it might be tricky but I'll have a look.

Btw can you give me more meaningful example of why would you like to auto-complete in the middle? I don't get this example above.

**Comment by zardoy** [comment]
Yes! I remembered two snippets, where this behavior was really annoying. Consider these extremely useful snippets:

```json
{
    "name": "moreArr",
    "description": "",
    "body": "[...{{expr}}, $1]",
    "when": ["identifier", "expression", "function-call"]
},
{
    "name": "moreObj",
    "description": "",
    "body": "{...{{expr}}, $1}",
    "when": ["identifier", "expression", "function-call"]
},
```

Example code:

```ts
const someStrings = ['I', 'love']

console.log(someStrings/*.moreArr*/.reduce((prev, str) => `${prev} ${str}`, ''))

// actual (see issue body for different cases)

console.log([...someStrings., ].reduce((prev, str) => `${prev} ${str}`, ''))

// expected

console.log([...someStrings, 'postfixes'].reduce((prev, str) => `${prev} ${str}`, ''))

// another example
```

Of course, I could wrap this expression into brackets and write `...` but I would lose a lot of time on this (that's why I use this extension!).

**Comment by ipatalas** [comment]
Cool, that makes sense, I'll have a look.

**Comment by ipatalas** [comment]
Published a fix
