### ISSUE TITLE
Postfixes should be suggested only after `.`

### ISSUE THREAD

**Issue by zardoy** [ipatalas/vscode-postfix-ts#64]
For now, postfixes are suggested after ` = ` and a few other characters (I can't remember other cases, sorry).

For example:

```ts
test.test = new // postfix is suggested, but it shouldn't appear here
```

Since as I suppose `name` can only be a single word (this is how builtin snippet works) why don't we check that character before current word is `.`?

**Comment by ipatalas** [comment]
Interesting... I didn't notice that before but you're right, it really gets triggered. That should be easy to fix as I already check if the dot exists in that line so it's just a matter of checking if it's on the right place in relation to the cursor.

**Comment by zardoy** [comment]
Hey, @ipatalas thanks for fixing the issue, but please release this on Marketplace

**Comment by ipatalas** [comment]
Sorry, didn't make it before holidays. I'll be back next week so please stay tuned.

**Comment by ipatalas** [comment]
New version published
