### ISSUE TITLE
can't work in shorter syntax for method definitions on object

### ISSUE THREAD

**Issue by qijizh** [ipatalas/vscode-postfix-ts#66]
It works perfectly in normal way of method definitions for objects, like `obj.fn1`  and `obj.fn2` , but can't work in shorter syntax for method definitions on objects, like `obj.fn3`.
```js
const obj = {
  fn1: function (params) {
    params.return    //works
  },
  fn2: (params) => {
    params.return    //works
  },
  fn3(params) {
    params.return    //can't work
  },
};
```
My English expression may not be very good, please forgive me

**Comment by ipatalas** [comment]
Found the problem, fix will be available in next release.

**Comment by ipatalas** [comment]
Fixed in new release, please update
