### ISSUE TITLE
doesn't work in binary-expression when right side is identifier

### ISSUE THREAD

**Issue by zardoy** [ipatalas/vscode-postfix-ts#67]
Hi! I found it useful to write equality expression first and then using your `binary-expression` when case.
However I doesn't seem to work if right side of the expression is.

Example of useful snippet:
```json
 {
    "name": "if",
    "body": "if ({{expr}}) ",
    "when": [
        "binary-expression"
    ]
},
```

Works well:

```ts
test === 'something'.if
```

Doesn't work well:

```ts
const userInput = 'something'
test === userInput.if
```

It doesn't even show the suggestion, however it is still binary expression, isn't it?

**Comment by ipatalas** [comment]
Yes, indeed, that is a valid binary expression. It just didn't work in some cases (quite a lot actually) but should be fixed in next version :)

**Comment by zardoy** [comment]
Works like a charm. Thank you!

Update: I thought it have problems, but everything is good! Thank you again!
