### ISSUE TITLE
Binary expression with equals regression

### ISSUE THREAD

**Issue by zardoy** [ipatalas/vscode-postfix-ts#77]
```ts
test = () => {
    wrapMe
}
```
Try to use `.log` after `wrapMe`:
```ts
console.log(test = () => {
wrapMe)
}
```
Results broken code, it doesn't seem to work anywhere in these functions.

Interesting fact that this is a binary expression with equals operator token.

**Comment by zardoy** [comment]
Its a regression and using previous version for now.

**Comment by zardoy** [comment]
Narrowed a bit example: `b = b.castas` -> `(b = b as )` but used to be  `b = (b as )`

**Comment by ipatalas** [comment]
Shoot, that was the fix for https://github.com/ipatalas/vscode-postfix-ts/issues/67 which broke it... it doesn't look that easy to fix to have both of them working. Need to think about it.

**Comment by ipatalas** [comment]
And yes, it looks like binary expression in AST for some reason. On the other hand it works well when using directly in declaration:
```ts
const test = () => {
  wrapMe.log
}

// or
const a = b.castas
```

As a quick "workaround" I can check if the binary expression has operator different than `=` (assignment rather than regular binary expression).

**Comment by ipatalas** [comment]
Just released a hotfix, thanks again for help!
