### ISSUE TITLE
Binary expression parentheses quickpick regression

### ISSUE THREAD

**Issue by zardoy** [ipatalas/vscode-postfix-ts#80]
Not suggesting multiple variants in these cases anymore:
`if (a > b && (x * 100){not})` or `if (b && (a > 50){not} && a)`
But we have the following test: `if (a > b && x * 100{not})` (without parentheses)

**Comment by ipatalas** [comment]
Found the bug. I will add another test for that to make sure it won't happen again ;)
...and I thought I've got pretty good test coverage here but yet you manage to find something new :D
Well done 🏅

**Comment by zardoy** [comment]
Hey! @ipatalas something weird started to happen in this case:

```ts
if (
        (a && (b &&
        a
        .a
        .b)).if
    )  {}
```

It was suggesting only `.not` template in this case, but now it also suggest `.if` with incorrect insertText

**Comment by ipatalas** [comment]
Are you sure it's not a custom template?
It works fine on my end:
![image](https://user-images.githubusercontent.com/2623329/192056032-342525ab-0686-4c3e-803e-56945bb3cc75.png)
`.not` is the only default template being suggested.
