### ISSUE TITLE
Shouldn't be suggested in JSX Elements & `JSXText`

### ISSUE THREAD

**Issue by zardoy** [ipatalas/vscode-postfix-ts#82]
Postfixes should not be suggested inside JSX text/Elements. Failing examples:

```tsx
;<>a.castas</>
;<p.promisify></p>
;<p test.not></p>
;<p className="thing.log"></p>
```

But support for `JSXExpression` should be preserved:
```tsx
;<p hidden={showMe.not}>test{thing.castas}</p>
```

**Comment by ipatalas** [comment]
Good idea, I see TS AST supports this so this will be easy, thanks for suggestion.
