### ISSUE TITLE
Inline snippets too high priority

### ISSUE THREAD

**Issue by CoenraadS** [ipatalas/vscode-postfix-ts#9]
In the latest insiders postfix snippets are ontop of all other suggestions. I believe this behaviour is  controlled by setting `CompletionItem.sortText`, however I couldn't solve it myself.

https://github.com/Microsoft/vscode/issues/26944

**Comment by ipatalas** [comment]
See my comment in the issue you linked.
I will put that on top of my list but can't promise any date as it looks like quite a lot of work.

It bothers me as well after VSCode update so I won't forget :)

**Comment by ipatalas** [comment]
It just got better:
![image](https://cloud.githubusercontent.com/assets/2623329/26524540/787300de-4336-11e7-996c-fecf9ec82331.png)

It was easier than I initially thought.

**Comment by CoenraadS** [comment]
It is better, but still not exactly the same as it used to be. I understand this is because of the vscode change, but I'm still looking for a way that when nothing is typed, snippets are bottom, and when typing starts it goes back to regular inline.

`this.item.sortText = 'z' + keyword;` gets me almost there, but then the priority is too low still for an exact match.

![image](https://cloud.githubusercontent.com/assets/5593825/26527760/ea18947e-439a-11e7-986a-3d0fefe4407d.png)
